### ISSUE TITLE
Error when pip install on the 5.0.x branch

### ISSUE THREAD

**Issue by rgeneaux** [PyMoDAQ/pymodaq_plugins_mockexamples#7]
Hi, 

I am getting an error when running `pip install git+https://github.com/PyMoDAQ/pymodaq_plugins_mockexamples`:

![image](https://github.com/user-attachments/assets/1006fbdf-219e-4212-bcdd-dce3eb39d644)

thanks!

**Comment by seb5g** [comment]
I've been working on a PR to include a patch for this and some other modification. Please test again

**Comment by rgeneaux** [comment]
it works, thanks! I have to use `--no-deps` because somehow my local pymodaq 5.0 is not recognized as >=5.0 but that is another issue.
